
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./bin/dev
    environment:
      RAILS_ENV: development
    volumes:
      - .:/rails
      - node_modules:/rails/node_modules
      - tmp-data:/rails/tmp
    ports:
      - "3000:3000"

volumes:
  node_modules:
  tmp-data: