ARG RUBY_VERSION=3.4.5
FROM ruby:$RUBY_VERSION-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      git \
      libyaml-dev \
      pkg-config \
      curl \
      libjemalloc2 \
      libvips \
      sqlite3 \
      nodejs \
      yarn \
      watchman \
    && rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

# RUN mkdir -p tmp/pids && chown -R 1000:1000 /rails

RUN groupadd --system --gid 1000 rails && \
    useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/bash && \
    mkdir -p tmp/pids && \
    chown -R rails:rails /rails

USER rails:rails

EXPOSE 3000

CMD ["./bin/dev"]